// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.cleanupOldItemsStmt, err = db.PrepareContext(ctx, cleanupOldItems); err != nil {
		return nil, fmt.Errorf("error preparing query CleanupOldItems: %w", err)
	}
	if q.deletePollingStateBySourceIDStmt, err = db.PrepareContext(ctx, deletePollingStateBySourceID); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePollingStateBySourceID: %w", err)
	}
	if q.deleteSourceStmt, err = db.PrepareContext(ctx, deleteSource); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSource: %w", err)
	}
	if q.getAllItemsStmt, err = db.PrepareContext(ctx, getAllItems); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllItems: %w", err)
	}
	if q.getAllSourcesStmt, err = db.PrepareContext(ctx, getAllSources); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllSources: %w", err)
	}
	if q.getItemsAfterStmt, err = db.PrepareContext(ctx, getItemsAfter); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemsAfter: %w", err)
	}
	if q.getItemsAfterAndSourceStmt, err = db.PrepareContext(ctx, getItemsAfterAndSource); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemsAfterAndSource: %w", err)
	}
	if q.getItemsAfterAndTypeStmt, err = db.PrepareContext(ctx, getItemsAfterAndType); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemsAfterAndType: %w", err)
	}
	if q.getItemsBySourceStmt, err = db.PrepareContext(ctx, getItemsBySource); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemsBySource: %w", err)
	}
	if q.getItemsBySourceAndTypeStmt, err = db.PrepareContext(ctx, getItemsBySourceAndType); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemsBySourceAndType: %w", err)
	}
	if q.getItemsByTypeStmt, err = db.PrepareContext(ctx, getItemsByType); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemsByType: %w", err)
	}
	if q.getLatestItemsStmt, err = db.PrepareContext(ctx, getLatestItems); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestItems: %w", err)
	}
	if q.getPollingStateStmt, err = db.PrepareContext(ctx, getPollingState); err != nil {
		return nil, fmt.Errorf("error preparing query GetPollingState: %w", err)
	}
	if q.getSourceStmt, err = db.PrepareContext(ctx, getSource); err != nil {
		return nil, fmt.Errorf("error preparing query GetSource: %w", err)
	}
	if q.getSourcesAndPollingStateStmt, err = db.PrepareContext(ctx, getSourcesAndPollingState); err != nil {
		return nil, fmt.Errorf("error preparing query GetSourcesAndPollingState: %w", err)
	}
	if q.insertOrReplaceItemStmt, err = db.PrepareContext(ctx, insertOrReplaceItem); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrReplaceItem: %w", err)
	}
	if q.insertOrReplaceItemsStmt, err = db.PrepareContext(ctx, insertOrReplaceItems); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrReplaceItems: %w", err)
	}
	if q.updateSourceStmt, err = db.PrepareContext(ctx, updateSource); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSource: %w", err)
	}
	if q.upsertPollingStateStmt, err = db.PrepareContext(ctx, upsertPollingState); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertPollingState: %w", err)
	}
	if q.upsertSourceStmt, err = db.PrepareContext(ctx, upsertSource); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSource: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.cleanupOldItemsStmt != nil {
		if cerr := q.cleanupOldItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanupOldItemsStmt: %w", cerr)
		}
	}
	if q.deletePollingStateBySourceIDStmt != nil {
		if cerr := q.deletePollingStateBySourceIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePollingStateBySourceIDStmt: %w", cerr)
		}
	}
	if q.deleteSourceStmt != nil {
		if cerr := q.deleteSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSourceStmt: %w", cerr)
		}
	}
	if q.getAllItemsStmt != nil {
		if cerr := q.getAllItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllItemsStmt: %w", cerr)
		}
	}
	if q.getAllSourcesStmt != nil {
		if cerr := q.getAllSourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllSourcesStmt: %w", cerr)
		}
	}
	if q.getItemsAfterStmt != nil {
		if cerr := q.getItemsAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemsAfterStmt: %w", cerr)
		}
	}
	if q.getItemsAfterAndSourceStmt != nil {
		if cerr := q.getItemsAfterAndSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemsAfterAndSourceStmt: %w", cerr)
		}
	}
	if q.getItemsAfterAndTypeStmt != nil {
		if cerr := q.getItemsAfterAndTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemsAfterAndTypeStmt: %w", cerr)
		}
	}
	if q.getItemsBySourceStmt != nil {
		if cerr := q.getItemsBySourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemsBySourceStmt: %w", cerr)
		}
	}
	if q.getItemsBySourceAndTypeStmt != nil {
		if cerr := q.getItemsBySourceAndTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemsBySourceAndTypeStmt: %w", cerr)
		}
	}
	if q.getItemsByTypeStmt != nil {
		if cerr := q.getItemsByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemsByTypeStmt: %w", cerr)
		}
	}
	if q.getLatestItemsStmt != nil {
		if cerr := q.getLatestItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestItemsStmt: %w", cerr)
		}
	}
	if q.getPollingStateStmt != nil {
		if cerr := q.getPollingStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPollingStateStmt: %w", cerr)
		}
	}
	if q.getSourceStmt != nil {
		if cerr := q.getSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSourceStmt: %w", cerr)
		}
	}
	if q.getSourcesAndPollingStateStmt != nil {
		if cerr := q.getSourcesAndPollingStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSourcesAndPollingStateStmt: %w", cerr)
		}
	}
	if q.insertOrReplaceItemStmt != nil {
		if cerr := q.insertOrReplaceItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrReplaceItemStmt: %w", cerr)
		}
	}
	if q.insertOrReplaceItemsStmt != nil {
		if cerr := q.insertOrReplaceItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrReplaceItemsStmt: %w", cerr)
		}
	}
	if q.updateSourceStmt != nil {
		if cerr := q.updateSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSourceStmt: %w", cerr)
		}
	}
	if q.upsertPollingStateStmt != nil {
		if cerr := q.upsertPollingStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertPollingStateStmt: %w", cerr)
		}
	}
	if q.upsertSourceStmt != nil {
		if cerr := q.upsertSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSourceStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	cleanupOldItemsStmt              *sql.Stmt
	deletePollingStateBySourceIDStmt *sql.Stmt
	deleteSourceStmt                 *sql.Stmt
	getAllItemsStmt                  *sql.Stmt
	getAllSourcesStmt                *sql.Stmt
	getItemsAfterStmt                *sql.Stmt
	getItemsAfterAndSourceStmt       *sql.Stmt
	getItemsAfterAndTypeStmt         *sql.Stmt
	getItemsBySourceStmt             *sql.Stmt
	getItemsBySourceAndTypeStmt      *sql.Stmt
	getItemsByTypeStmt               *sql.Stmt
	getLatestItemsStmt               *sql.Stmt
	getPollingStateStmt              *sql.Stmt
	getSourceStmt                    *sql.Stmt
	getSourcesAndPollingStateStmt    *sql.Stmt
	insertOrReplaceItemStmt          *sql.Stmt
	insertOrReplaceItemsStmt         *sql.Stmt
	updateSourceStmt                 *sql.Stmt
	upsertPollingStateStmt           *sql.Stmt
	upsertSourceStmt                 *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		cleanupOldItemsStmt:              q.cleanupOldItemsStmt,
		deletePollingStateBySourceIDStmt: q.deletePollingStateBySourceIDStmt,
		deleteSourceStmt:                 q.deleteSourceStmt,
		getAllItemsStmt:                  q.getAllItemsStmt,
		getAllSourcesStmt:                q.getAllSourcesStmt,
		getItemsAfterStmt:                q.getItemsAfterStmt,
		getItemsAfterAndSourceStmt:       q.getItemsAfterAndSourceStmt,
		getItemsAfterAndTypeStmt:         q.getItemsAfterAndTypeStmt,
		getItemsBySourceStmt:             q.getItemsBySourceStmt,
		getItemsBySourceAndTypeStmt:      q.getItemsBySourceAndTypeStmt,
		getItemsByTypeStmt:               q.getItemsByTypeStmt,
		getLatestItemsStmt:               q.getLatestItemsStmt,
		getPollingStateStmt:              q.getPollingStateStmt,
		getSourceStmt:                    q.getSourceStmt,
		getSourcesAndPollingStateStmt:    q.getSourcesAndPollingStateStmt,
		insertOrReplaceItemStmt:          q.insertOrReplaceItemStmt,
		insertOrReplaceItemsStmt:         q.insertOrReplaceItemsStmt,
		updateSourceStmt:                 q.updateSourceStmt,
		upsertPollingStateStmt:           q.upsertPollingStateStmt,
		upsertSourceStmt:                 q.upsertSourceStmt,
	}
}
