// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Items struct {
	ID          string         `json:"id"`
	SourceID    sql.NullString `json:"source_id"`
	Title       sql.NullString `json:"title"`
	Author      sql.NullString `json:"author"`
	Description sql.NullString `json:"description"`
	Link        sql.NullString `json:"link"`
	Source      sql.NullString `json:"source"`
	PublishedAt sql.NullString `json:"published_at"`
	Type        sql.NullString `json:"type"`
	Enclosure   sql.NullString `json:"enclosure"`
	Duration    sql.NullInt64  `json:"duration"`
	Thumbnail   sql.NullString `json:"thumbnail"`
}

type PollingState struct {
	SourceID            string         `json:"source_id"`
	LastSuccessfulPoll  sql.NullString `json:"last_successful_poll"`
	ConsecutiveFailures sql.NullInt64  `json:"consecutive_failures"`
	LastError           sql.NullString `json:"last_error"`
	LastPolledAt        sql.NullString `json:"last_polled_at"`
}

type Sources struct {
	ID           string         `json:"id"`
	DisplayName  sql.NullString `json:"display_name"`
	FeedUrl      sql.NullString `json:"feed_url"`
	PollInterval sql.NullString `json:"poll_interval"`
	TypeHint     sql.NullString `json:"type_hint"`
}
