// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const cleanupOldItems = `-- name: CleanupOldItems :exec
DELETE FROM items WHERE published_at < datetime('now', '-30 days')
`

// Cleanup old items
func (q *Queries) CleanupOldItems(ctx context.Context) error {
	_, err := q.exec(ctx, q.cleanupOldItemsStmt, cleanupOldItems)
	return err
}

const deletePollingStateBySourceID = `-- name: DeletePollingStateBySourceID :exec
DELETE FROM polling_state WHERE source_id = ?
`

// Delete polling state for a removed source
func (q *Queries) DeletePollingStateBySourceID(ctx context.Context, sourceID string) error {
	_, err := q.exec(ctx, q.deletePollingStateBySourceIDStmt, deletePollingStateBySourceID, sourceID)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = ?
`

// Delete source by ID
func (q *Queries) DeleteSource(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSourceStmt, deleteSource, id)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, source_id, title, author, description, link, source, published_at, type, enclosure, duration, thumbnail FROM items ORDER BY published_at DESC LIMIT ? OFFSET ?
`

type GetAllItemsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

// Get all items with pagination
func (q *Queries) GetAllItems(ctx context.Context, arg GetAllItemsParams) ([]Items, error) {
	rows, err := q.query(ctx, q.getAllItemsStmt, getAllItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Items
	for rows.Next() {
		var i Items
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Link,
			&i.Source,
			&i.PublishedAt,
			&i.Type,
			&i.Enclosure,
			&i.Duration,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSources = `-- name: GetAllSources :many
SELECT
    id,
    display_name,
    feed_url,
    poll_interval,
    type_hint
FROM sources
ORDER BY id
`

// Get all sources
func (q *Queries) GetAllSources(ctx context.Context) ([]Sources, error) {
	rows, err := q.query(ctx, q.getAllSourcesStmt, getAllSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sources
	for rows.Next() {
		var i Sources
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.FeedUrl,
			&i.PollInterval,
			&i.TypeHint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsAfter = `-- name: GetItemsAfter :many
SELECT id, source_id, title, author, description, link, source, published_at, type, enclosure, duration, thumbnail
FROM items
WHERE
    published_at > ?
ORDER BY published_at DESC
LIMIT ?
OFFSET
    ?
`

type GetItemsAfterParams struct {
	PublishedAt sql.NullString `json:"published_at"`
	Limit       int64          `json:"limit"`
	Offset      int64          `json:"offset"`
}

// Get items published after a certain time with pagination
func (q *Queries) GetItemsAfter(ctx context.Context, arg GetItemsAfterParams) ([]Items, error) {
	rows, err := q.query(ctx, q.getItemsAfterStmt, getItemsAfter, arg.PublishedAt, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Items
	for rows.Next() {
		var i Items
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Link,
			&i.Source,
			&i.PublishedAt,
			&i.Type,
			&i.Enclosure,
			&i.Duration,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsAfterAndSource = `-- name: GetItemsAfterAndSource :many
SELECT id, source_id, title, author, description, link, source, published_at, type, enclosure, duration, thumbnail
FROM items
WHERE
    published_at > ?
    AND source_id = ?
ORDER BY published_at DESC
LIMIT ?
OFFSET
    ?
`

type GetItemsAfterAndSourceParams struct {
	PublishedAt sql.NullString `json:"published_at"`
	SourceID    sql.NullString `json:"source_id"`
	Limit       int64          `json:"limit"`
	Offset      int64          `json:"offset"`
}

// Get items published after a certain time and by source with pagination
func (q *Queries) GetItemsAfterAndSource(ctx context.Context, arg GetItemsAfterAndSourceParams) ([]Items, error) {
	rows, err := q.query(ctx, q.getItemsAfterAndSourceStmt, getItemsAfterAndSource,
		arg.PublishedAt,
		arg.SourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Items
	for rows.Next() {
		var i Items
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Link,
			&i.Source,
			&i.PublishedAt,
			&i.Type,
			&i.Enclosure,
			&i.Duration,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsAfterAndType = `-- name: GetItemsAfterAndType :many
SELECT id, source_id, title, author, description, link, source, published_at, type, enclosure, duration, thumbnail
FROM items
WHERE
    published_at > ?
    AND type = ?
ORDER BY published_at DESC
LIMIT ?
OFFSET
    ?
`

type GetItemsAfterAndTypeParams struct {
	PublishedAt sql.NullString `json:"published_at"`
	Type        sql.NullString `json:"type"`
	Limit       int64          `json:"limit"`
	Offset      int64          `json:"offset"`
}

// Get items published after a certain time and by type with pagination
func (q *Queries) GetItemsAfterAndType(ctx context.Context, arg GetItemsAfterAndTypeParams) ([]Items, error) {
	rows, err := q.query(ctx, q.getItemsAfterAndTypeStmt, getItemsAfterAndType,
		arg.PublishedAt,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Items
	for rows.Next() {
		var i Items
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Link,
			&i.Source,
			&i.PublishedAt,
			&i.Type,
			&i.Enclosure,
			&i.Duration,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsBySource = `-- name: GetItemsBySource :many
SELECT id, source_id, title, author, description, link, source, published_at, type, enclosure, duration, thumbnail
FROM items
WHERE
    source_id = ?
ORDER BY published_at DESC
LIMIT ?
OFFSET
    ?
`

type GetItemsBySourceParams struct {
	SourceID sql.NullString `json:"source_id"`
	Limit    int64          `json:"limit"`
	Offset   int64          `json:"offset"`
}

// Get items by source ID with pagination
func (q *Queries) GetItemsBySource(ctx context.Context, arg GetItemsBySourceParams) ([]Items, error) {
	rows, err := q.query(ctx, q.getItemsBySourceStmt, getItemsBySource, arg.SourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Items
	for rows.Next() {
		var i Items
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Link,
			&i.Source,
			&i.PublishedAt,
			&i.Type,
			&i.Enclosure,
			&i.Duration,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsBySourceAndType = `-- name: GetItemsBySourceAndType :many
SELECT id, source_id, title, author, description, link, source, published_at, type, enclosure, duration, thumbnail
FROM items
WHERE
    source_id = ?
    AND type = ?
ORDER BY published_at DESC
LIMIT ?
OFFSET
    ?
`

type GetItemsBySourceAndTypeParams struct {
	SourceID sql.NullString `json:"source_id"`
	Type     sql.NullString `json:"type"`
	Limit    int64          `json:"limit"`
	Offset   int64          `json:"offset"`
}

// Get items by source ID and type with pagination
func (q *Queries) GetItemsBySourceAndType(ctx context.Context, arg GetItemsBySourceAndTypeParams) ([]Items, error) {
	rows, err := q.query(ctx, q.getItemsBySourceAndTypeStmt, getItemsBySourceAndType,
		arg.SourceID,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Items
	for rows.Next() {
		var i Items
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Link,
			&i.Source,
			&i.PublishedAt,
			&i.Type,
			&i.Enclosure,
			&i.Duration,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByType = `-- name: GetItemsByType :many
SELECT id, source_id, title, author, description, link, source, published_at, type, enclosure, duration, thumbnail
FROM items
WHERE
    type = ?
ORDER BY published_at DESC
LIMIT ?
OFFSET
    ?
`

type GetItemsByTypeParams struct {
	Type   sql.NullString `json:"type"`
	Limit  int64          `json:"limit"`
	Offset int64          `json:"offset"`
}

// Get items by type with pagination
func (q *Queries) GetItemsByType(ctx context.Context, arg GetItemsByTypeParams) ([]Items, error) {
	rows, err := q.query(ctx, q.getItemsByTypeStmt, getItemsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Items
	for rows.Next() {
		var i Items
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Link,
			&i.Source,
			&i.PublishedAt,
			&i.Type,
			&i.Enclosure,
			&i.Duration,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestItems = `-- name: GetLatestItems :many
SELECT id, source_id, title, author, description, link, source, published_at, type, enclosure, duration, thumbnail FROM items ORDER BY published_at DESC LIMIT ?
`

// Get the latest N items ordered by published_at desc
func (q *Queries) GetLatestItems(ctx context.Context, limit int64) ([]Items, error) {
	rows, err := q.query(ctx, q.getLatestItemsStmt, getLatestItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Items
	for rows.Next() {
		var i Items
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Link,
			&i.Source,
			&i.PublishedAt,
			&i.Type,
			&i.Enclosure,
			&i.Duration,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollingState = `-- name: GetPollingState :one
SELECT
    source_id,
    last_successful_poll,
    consecutive_failures,
    last_error,
    last_polled_at
FROM polling_state
WHERE
    source_id = ?
`

// Get the polling state for a source
func (q *Queries) GetPollingState(ctx context.Context, sourceID string) (PollingState, error) {
	row := q.queryRow(ctx, q.getPollingStateStmt, getPollingState, sourceID)
	var i PollingState
	err := row.Scan(
		&i.SourceID,
		&i.LastSuccessfulPoll,
		&i.ConsecutiveFailures,
		&i.LastError,
		&i.LastPolledAt,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT
    id,
    display_name,
    feed_url,
    poll_interval,
    type_hint
FROM sources
WHERE
    id = ?
`

// Get source by ID
func (q *Queries) GetSource(ctx context.Context, id string) (Sources, error) {
	row := q.queryRow(ctx, q.getSourceStmt, getSource, id)
	var i Sources
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.FeedUrl,
		&i.PollInterval,
		&i.TypeHint,
	)
	return i, err
}

const getSourcesAndPollingState = `-- name: GetSourcesAndPollingState :many
SELECT s.id, s.display_name, s.feed_url, s.poll_interval, s.type_hint, p.last_successful_poll, p.consecutive_failures, p.last_error, p.last_polled_at
FROM sources s
    LEFT JOIN polling_state p ON s.id = p.source_id
WHERE (
        ?1 IS NULL
        OR s.id = ?1
    )
ORDER BY s.id
`

type GetSourcesAndPollingStateRow struct {
	ID                  string         `json:"id"`
	DisplayName         sql.NullString `json:"display_name"`
	FeedUrl             sql.NullString `json:"feed_url"`
	PollInterval        sql.NullString `json:"poll_interval"`
	TypeHint            sql.NullString `json:"type_hint"`
	LastSuccessfulPoll  sql.NullString `json:"last_successful_poll"`
	ConsecutiveFailures sql.NullInt64  `json:"consecutive_failures"`
	LastError           sql.NullString `json:"last_error"`
	LastPolledAt        sql.NullString `json:"last_polled_at"`
}

// Get sources along with their polling state (pass NULL to get all, or an ID to get one)
func (q *Queries) GetSourcesAndPollingState(ctx context.Context, id interface{}) ([]GetSourcesAndPollingStateRow, error) {
	rows, err := q.query(ctx, q.getSourcesAndPollingStateStmt, getSourcesAndPollingState, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSourcesAndPollingStateRow
	for rows.Next() {
		var i GetSourcesAndPollingStateRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.FeedUrl,
			&i.PollInterval,
			&i.TypeHint,
			&i.LastSuccessfulPoll,
			&i.ConsecutiveFailures,
			&i.LastError,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrReplaceItem = `-- name: InsertOrReplaceItem :one
INSERT
    OR
REPLACE INTO
    items (
        id,
        source_id,
        title,
        description,
        link,
        source,
        published_at,
        type,
        enclosure,
        duration,
        thumbnail
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    ) RETURNING id, source_id, title, author, description, link, source, published_at, type, enclosure, duration, thumbnail
`

type InsertOrReplaceItemParams struct {
	ID          string         `json:"id"`
	SourceID    sql.NullString `json:"source_id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	Link        sql.NullString `json:"link"`
	Source      sql.NullString `json:"source"`
	PublishedAt sql.NullString `json:"published_at"`
	Type        sql.NullString `json:"type"`
	Enclosure   sql.NullString `json:"enclosure"`
	Duration    sql.NullInt64  `json:"duration"`
	Thumbnail   sql.NullString `json:"thumbnail"`
}

// Insert or update a feed item (handle duplicates)
func (q *Queries) InsertOrReplaceItem(ctx context.Context, arg InsertOrReplaceItemParams) (Items, error) {
	row := q.queryRow(ctx, q.insertOrReplaceItemStmt, insertOrReplaceItem,
		arg.ID,
		arg.SourceID,
		arg.Title,
		arg.Description,
		arg.Link,
		arg.Source,
		arg.PublishedAt,
		arg.Type,
		arg.Enclosure,
		arg.Duration,
		arg.Thumbnail,
	)
	var i Items
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.Link,
		&i.Source,
		&i.PublishedAt,
		&i.Type,
		&i.Enclosure,
		&i.Duration,
		&i.Thumbnail,
	)
	return i, err
}

const insertOrReplaceItems = `-- name: InsertOrReplaceItems :many
INSERT
    OR
REPLACE INTO
    items (
        id,
        source_id,
        title,
        description,
        link,
        source,
        published_at,
        type,
        enclosure,
        duration,
        thumbnail
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    ) RETURNING id, source_id, title, author, description, link, source, published_at, type, enclosure, duration, thumbnail
`

type InsertOrReplaceItemsParams struct {
	ID          string         `json:"id"`
	SourceID    sql.NullString `json:"source_id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	Link        sql.NullString `json:"link"`
	Source      sql.NullString `json:"source"`
	PublishedAt sql.NullString `json:"published_at"`
	Type        sql.NullString `json:"type"`
	Enclosure   sql.NullString `json:"enclosure"`
	Duration    sql.NullInt64  `json:"duration"`
	Thumbnail   sql.NullString `json:"thumbnail"`
}

// insert many items with a single query
func (q *Queries) InsertOrReplaceItems(ctx context.Context, arg InsertOrReplaceItemsParams) ([]Items, error) {
	rows, err := q.query(ctx, q.insertOrReplaceItemsStmt, insertOrReplaceItems,
		arg.ID,
		arg.SourceID,
		arg.Title,
		arg.Description,
		arg.Link,
		arg.Source,
		arg.PublishedAt,
		arg.Type,
		arg.Enclosure,
		arg.Duration,
		arg.Thumbnail,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Items
	for rows.Next() {
		var i Items
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Link,
			&i.Source,
			&i.PublishedAt,
			&i.Type,
			&i.Enclosure,
			&i.Duration,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSource = `-- name: UpdateSource :exec
UPDATE sources
SET
    display_name = ?,
    feed_url = ?,
    poll_interval = ?,
    type_hint = ?
WHERE
    id = ?
`

type UpdateSourceParams struct {
	DisplayName  sql.NullString `json:"display_name"`
	FeedUrl      sql.NullString `json:"feed_url"`
	PollInterval sql.NullString `json:"poll_interval"`
	TypeHint     sql.NullString `json:"type_hint"`
	ID           string         `json:"id"`
}

// Update source metadata
func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) error {
	_, err := q.exec(ctx, q.updateSourceStmt, updateSource,
		arg.DisplayName,
		arg.FeedUrl,
		arg.PollInterval,
		arg.TypeHint,
		arg.ID,
	)
	return err
}

const upsertPollingState = `-- name: UpsertPollingState :exec
INSERT INTO
    polling_state (
        source_id,
        last_successful_poll,
        consecutive_failures,
        last_error,
        last_polled_at
    )
VALUES (?, ?, ?, ?, ?) ON CONFLICT (source_id) DO
UPDATE
SET
    last_successful_poll = excluded.last_successful_poll,
    consecutive_failures = excluded.consecutive_failures,
    last_error = excluded.last_error,
    last_polled_at = excluded.last_polled_at
`

type UpsertPollingStateParams struct {
	SourceID            string         `json:"source_id"`
	LastSuccessfulPoll  sql.NullString `json:"last_successful_poll"`
	ConsecutiveFailures sql.NullInt64  `json:"consecutive_failures"`
	LastError           sql.NullString `json:"last_error"`
	LastPolledAt        sql.NullString `json:"last_polled_at"`
}

// Upsert polling state for a source
func (q *Queries) UpsertPollingState(ctx context.Context, arg UpsertPollingStateParams) error {
	_, err := q.exec(ctx, q.upsertPollingStateStmt, upsertPollingState,
		arg.SourceID,
		arg.LastSuccessfulPoll,
		arg.ConsecutiveFailures,
		arg.LastError,
		arg.LastPolledAt,
	)
	return err
}

const upsertSource = `-- name: UpsertSource :exec
INSERT
    OR
REPLACE INTO
    sources (
        id,
        display_name,
        feed_url,
        poll_interval,
        type_hint
    )
VALUES (?, ?, ?, ?, ?)
`

type UpsertSourceParams struct {
	ID           string         `json:"id"`
	DisplayName  sql.NullString `json:"display_name"`
	FeedUrl      sql.NullString `json:"feed_url"`
	PollInterval sql.NullString `json:"poll_interval"`
	TypeHint     sql.NullString `json:"type_hint"`
}

// Upsert source metadata
func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) error {
	_, err := q.exec(ctx, q.upsertSourceStmt, upsertSource,
		arg.ID,
		arg.DisplayName,
		arg.FeedUrl,
		arg.PollInterval,
		arg.TypeHint,
	)
	return err
}
